

<!ELEMENT circuito (
  nombre,
  longitud_circuito,
  anchura_media,
  fecha,
  hora_inicio,
  vueltas,
  localidad,
  pais,
  patrocinador,
  referencias,
  galeria_fotos,
  galeria_videos,
  punto_origen,
  tramos,
  resultado_carrera,
  clasificacion_mundial
)>

<!ELEMENT nombre (#PCDATA)>

<!ELEMENT longitud_circuito (#PCDATA)>
<!ATTLIST longitud_circuito
  unidad (m) "m"
>

<!ELEMENT anchura_media (#PCDATA)>
<!ATTLIST anchura_media
  unidad (m) "m"
>

<!ELEMENT fecha (#PCDATA)>
<!ATTLIST fecha
  formato CDATA   "DD-MM-YYYY"
>

<!ELEMENT hora_inicio (#PCDATA)>
<!ATTLIST hora_inicio
  tz      CDATA   "Europe/Madrid"
  formato CDATA   "HH:MM"
>

<!ELEMENT vueltas (#PCDATA)>

<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT patrocinador (#PCDATA)>

<!ELEMENT referencias (referencia, referencia, referencia, referencia*)>
<!ELEMENT referencia (#PCDATA)>

<!ELEMENT galeria_fotos (foto, foto?, foto?, foto?, foto?)>
<!ELEMENT foto EMPTY>
<!ATTLIST foto
  archivo CDATA #REQUIRED
  titulo  CDATA #IMPLIED
>

<!ELEMENT galeria_videos (video, video?, video?)>
<!ELEMENT video EMPTY>
<!ATTLIST video
  archivo CDATA #REQUIRED 
  titulo  CDATA #IMPLIED
  formato CDATA #IMPLIED
>

<!ELEMENT punto_origen (latitud,longitud,altitud)>
<!ELEMENT latitud  (#PCDATA)>
<!ATTLIST latitud  unidad (deg) "deg">
<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud unidad (deg) "deg">
<!ELEMENT altitud  (#PCDATA)>
<!ATTLIST altitud  unidad (m)   "m">

<!ELEMENT tramos (tramo+)>
<!ELEMENT tramo (distancia, punto_final, numero_sector)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia
  unidad (m)    "m"
>
<!ELEMENT punto_final (longitud, latitud, altitud)>
<!ELEMENT numero_sector (#PCDATA)>

<!ELEMENT resultado_carrera (vencedor, tiempo_total)>
<!ELEMENT vencedor (#PCDATA)>
<!ELEMENT tiempo_total (#PCDATA)>
<!ATTLIST tiempo_total
  formato CDATA "MM:SS.mmm"
>

<!ELEMENT clasificacion_mundial (piloto, piloto, piloto)>
<!ELEMENT piloto (#PCDATA)>
<!ATTLIST piloto
  posicion (1|2|3) #REQUIRED
>
